In [1]:
# ================================lect. 5 date - 27-01-2022 =================================#

# ============ PANDAS ===========
# BUILD IN MODEL
# DO MODEL - NUMERIC, NO NULL
# DATACLEAN 
# MODEL BUILDING
# read the file
# srore it [variabel] = fun - pd.read_csv (path, file name, format )

import numpy as np
import pandas as pd
cr = pd.read_csv(r"F:\DS\PANDAS 2\CreditRisk.csv ")
cr
cr.Gender         = cr.Gender.fillna('Male')  # correct
cr.Dependents     =cr.Dependents.fillna(0)
cr.Self_Employed  = cr.Self_Employed.fillna('No')
cr.LoanAmount  = cr.LoanAmount.fillna(cr.LoanAmount.mean()   )
cr.Loan_Amount_Term  = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean())
cr.Credit_History  = cr.Credit_History.fillna(0)
cr = cr.dropna()


cr.Gender  = cr.Gender.replace({ 'Male':0 , 'Female':1})
cr.Self_Employed.replace({'No':0 , 'Yes': 1} , inplace = True)

cr.Married.replace({'Yes':1 , 'No':0}, inplace= True)
cr.Education.replace({'Graduate':1 , 'Not Graduate':0}, inplace= True)
cr.Property_Area.replace({'Semiurban': 1 , 'Rural': 0 , 'Urban': 2 }  , inplace= True)
cr.Loan_Status.replace({'Y':1 , 'N':0  } , inplace= True)
cr = cr.drop(['Loan_ID'],axis = 1)
cr_x=cr.iloc[:,:-1]
cr_y=cr.iloc[:,-1]
cr_x1 = cr_x
cr_x =np.array(cr_x)
cr_y =np.array(cr_y)





In [2]:
cr.columns[cr.isnull().sum() > 0]   # check

Index([], dtype='object')

In [3]:
cr.columns[cr.dtypes == 'object']  # check

Index([], dtype='object')

In [4]:
from sklearn.model_selection import train_test_split # required import

In [5]:
train_cr , test_cr = train_test_split( cr , test_size = 0.2)

In [6]:
print(cr.shape)
print(train_cr.shape)
print(test_cr.shape)

(978, 12)
(782, 12)
(196, 12)


In [11]:
pip install boruta

In [7]:
from sklearn.ensemble import RandomForestClassifier
from boruta import BorutaPy  
import numpy as np


In [8]:
cr_x = np.array(cr_x)
cr_y = np.array(cr_y)

In [9]:
rfc = RandomForestClassifier()

In [ ]:
boruta_feature_selector = BorutaPy(rfc,   max_iter = 30 , verbose=2)
boruta_feature_selector.fit(cr_x , cr_y )

Iteration: 	1 / 30
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	2 / 30
Confirmed: 	0
Tentative: 	11
Rejected: 	0
Iteration: 	3 / 30
Confirmed: 	0
Tentative: 	11
Rejected: 	0


In [16]:
boruta_feature_selector.support_

array([False, False, False, False, False, False, False, False, False,
        True, False])

In [11]:
cr_x1.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [13]:
# true id for confirmed important
# false ( rejected and tentative)

In [14]:
x_coef = pd.DataFrame({'Features':cr_x1.columns , "Coeff":boruta_feature_selector.support_ } )
x_coef

Features  Coeff
0              Gender  False
1             Married  False
2          Dependents  False
3           Education  False
4       Self_Employed  False
5     ApplicantIncome  False
6   CoapplicantIncome  False
7          LoanAmount  False
8    Loan_Amount_Term  False
9      Credit_History   True
10      Property_Area  False

In [15]:
x_coef.sort_values('Coeff' , ascending = False)

Features  Coeff
9      Credit_History   True
0              Gender  False
1             Married  False
2          Dependents  False
3           Education  False
4       Self_Employed  False
5     ApplicantIncome  False
6   CoapplicantIncome  False
7          LoanAmount  False
8    Loan_Amount_Term  False
10      Property_Area  False

In [5]:
# ================================lect. 5 date - 27-01-2022 =================================#

# ============ PANDAS ===========
# BUILD IN MODEL
# DO MODEL - NUMERIC, NO NULL
# DATACLEAN 
# MODEL BUILDING
# read the file
# srore it [variabel] = fun - pd.read_csv (path, file name, format )

import numpy as np
import pandas as pd
cr = pd.read_csv(r"F:\DS\PANDAS 2\CreditRisk.csv ")
cr
cr.Gender         = cr.Gender.fillna('Male')  # correct
cr.Dependents     =cr.Dependents.fillna(0)
cr.Self_Employed  = cr.Self_Employed.fillna('No')
cr.LoanAmount  = cr.LoanAmount.fillna(cr.LoanAmount.mean()   )
cr.Loan_Amount_Term  = cr.Loan_Amount_Term.fillna(cr.Loan_Amount_Term.mean())
cr.Credit_History  = cr.Credit_History.fillna(0)
cr = cr.dropna()


cr.Gender  = cr.Gender.replace({ 'Male':0 , 'Female':1})
cr.Self_Employed.replace({'No':0 , 'Yes': 1} , inplace = True)

cr.Married.replace({'Yes':1 , 'No':0}, inplace= True)
cr.Education.replace({'Graduate':1 , 'Not Graduate':0}, inplace= True)
cr.Property_Area.replace({'Semiurban': 1 , 'Rural': 0 , 'Urban': 2 }  , inplace= True)
cr.Loan_Status.replace({'Y':1 , 'N':0  } , inplace= True)
cr = cr.drop(['Loan_ID'],axis = 1)
cr_x=cr.iloc[:,:-1]
cr_y=cr.iloc[:,-1]


In [10]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [11]:
from sklearn.feature_selection import RFE
rfe = RFE(dt  , 9)

In [12]:
rfe.fit(cr_x, cr_y)

RFE(estimator=DecisionTreeClassifier(), n_features_to_select=9)

In [13]:
rfe.support_

array([ True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True])

In [18]:
cr_x.columns

Index(['Gender', 'Married', 'Dependents', 'Education', 'Self_Employed',
       'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [19]:
feat_sig = pd.DataFrame({'columns':cr_x.columns , "Imp":rfe.support_ } )
feat_sig

columns    Imp
0              Gender   True
1             Married   True
2          Dependents   True
3           Education  False
4       Self_Employed  False
5     ApplicantIncome   True
6   CoapplicantIncome   True
7          LoanAmount   True
8    Loan_Amount_Term   True
9      Credit_History   True
10      Property_Area   True

In [20]:
feat_sig.sort_values('Imp' , ascending = False)

columns    Imp
0              Gender   True
1             Married   True
2          Dependents   True
5     ApplicantIncome   True
6   CoapplicantIncome   True
7          LoanAmount   True
8    Loan_Amount_Term   True
9      Credit_History   True
10      Property_Area   True
3           Education  False
4       Self_Employed  False

 # adaboosting

In [21]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
abc = AdaBoostClassifier()
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [22]:
abc.fit(cr_x , cr_y)

AdaBoostClassifier()

In [23]:
abc.predict(cr_x)

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,