DT ==== DECISION TREEE

In [1]:
import pandas as pd
ch = pd.read_csv(r"F:\DS\ML\Churn.csv ")

In [2]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   object 
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   object 
 4   Dependents        7043 non-null   object 
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   object 
 7   MultipleLines     7043 non-null   object 
 8   InternetService   7043 non-null   object 
 9   OnlineSecurity    7043 non-null   object 
 10  OnlineBackup      7043 non-null   object 
 11  DeviceProtection  7043 non-null   object 
 12  TechSupport       7043 non-null   object 
 13  StreamingTV       7043 non-null   object 
 14  StreamingMovies   7043 non-null   object 
 15  Contract          7043 non-null   object 
 16  PaperlessBilling  7043 non-null   object 


In [3]:
ch.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [5]:
ch.gender = le.fit_transform(ch.gender)

In [6]:
ch.gender =le.fit_transform(ch.gender)
ch.Partner=le.fit_transform(ch.Partner)
ch.Dependents =le.fit_transform(ch.Dependents)
ch.PhoneService=le.fit_transform(ch.PhoneService)
ch.MultipleLines=ch.MultipleLines.replace({'No phone service':1,'No':0,'Yes':2})
ch.InternetService=ch.MultipleLines.replace({'DSL':1,'No':0,'Fiber optic':2})
ch.OnlineSecurity=ch.OnlineSecurity.replace({'No':1,'No internet service':0,'Yes':2})
ch.OnlineBackup = ch.OnlineBackup.replace({'No internet service':0, 'No':1, 'Yes': 2})
ch.DeviceProtection=ch.DeviceProtection.replace({'No':1,'No internet service':0,'Yes':2})
ch.TechSupport=ch.TechSupport.replace({'No':1,'No internet service':0,'Yes':2})
ch.StreamingTV=ch.StreamingTV.replace({'No':1,'No internet service':0,'Yes':2})
ch.StreamingMovies=ch.StreamingMovies.replace({'No':1,'No internet service':0,'Yes':2})
ch.Contract=ch.Contract.replace({'One year':1,'Month-to-month':0,'Two year':2})
ch.PaperlessBilling=ch.PaperlessBilling.replace({'Yes':1,'No':0})
ch.PaymentMethod =le.fit_transform(ch.PaymentMethod)
ch.Churn=le.fit_transform(ch.Churn)

In [7]:
ch.TotalCharges.value_counts()  # here some blanks are presents so convert it into null

          11
20.2      11
19.75      9
20.05      8
19.9       8
          ..
6849.4     1
692.35     1
130.15     1
3211.9     1
6844.5     1
Name: TotalCharges, Length: 6531, dtype: int64

In [8]:
ch.TotalCharges.isnull().sum()

0

In [9]:
import numpy as np
ch.TotalCharges = ch.TotalCharges.replace(' ', np.nan)
ch.TotalCharges = ch.TotalCharges.astype('float')
ch.TotalCharges = ch.TotalCharges.fillna(ch.TotalCharges.mean())

In [10]:
ch.TotalCharges.isnull().sum()

0

In [11]:
ch.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        7043 non-null   object 
 1   gender            7043 non-null   int64  
 2   SeniorCitizen     7043 non-null   int64  
 3   Partner           7043 non-null   int32  
 4   Dependents        7043 non-null   int32  
 5   tenure            7043 non-null   int64  
 6   PhoneService      7043 non-null   int32  
 7   MultipleLines     7043 non-null   int64  
 8   InternetService   7043 non-null   int64  
 9   OnlineSecurity    7043 non-null   int64  
 10  OnlineBackup      7043 non-null   int64  
 11  DeviceProtection  7043 non-null   int64  
 12  TechSupport       7043 non-null   int64  
 13  StreamingTV       7043 non-null   int64  
 14  StreamingMovies   7043 non-null   int64  
 15  Contract          7043 non-null   int64  
 16  PaperlessBilling  7043 non-null   int64  


In [12]:
ch = ch.drop(['customerID'] , axis = 1)

In [13]:
from sklearn.model_selection import train_test_split

In [16]:
ch_train, ch_test = train_test_split(ch , test_size = 0.2)

In [17]:
ch_train_x = ch_train.iloc[: , 0:-1]
ch_train_y = ch_train.iloc[: , -1]

In [18]:
ch_test_x = ch_test.iloc[: , 0:-1]
ch_test_y = ch_test.iloc[: , -1]

In [19]:
from sklearn.linear_model import LogisticRegression
log_ch = LogisticRegression()

In [20]:
log_ch.fit(ch_train_x , ch_train_y)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [21]:
pred_test = log_ch.predict(ch_test_x)
pred_test

array([0, 0, 0, ..., 0, 0, 0])

In [22]:
from sklearn import metrics
mat=metrics.confusion_matrix(ch_test_y,pred_test)
mat

array([[941, 103],
       [165, 200]], dtype=int64)

In [23]:
metrics.accuracy_score(ch_test_y,pred_test)

0.8097941802696949

In [24]:
metrics.recall_score(ch_test_y,pred_test)

0.547945205479452

In [25]:
metrics.f1_score(ch_test_y,pred_test)

0.5988023952095809

In [26]:
error = mat[0][1] / mat[0].sum()
error

0.09865900383141762

In [27]:
mat

array([[941, 103],
       [165, 200]], dtype=int64)

In [28]:
(941+200)/(941+103+165+200)

0.8097941802696949

In [29]:
import numpy as np

In [30]:
# -0.9*np.log2(0.9) + - 0.1*np.log2(0.1)

In [33]:
# -0.5*np.log2(0.5) + - 0.5*np.log2(0.5)

In [34]:
# lets build the model using disicion tree
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()

In [35]:
dt.fit(ch_train_x , ch_train_y)

DecisionTreeClassifier()

In [36]:
pred_dt = dt.predict(ch_test_x)