In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
import tensorflow as tf
import keras

In [3]:
mnist = pd.read_csv(r'F:\DS\KAGGLE DATASET\Neural Network\mnist data\mnist_test.csv')

In [4]:
mnist.head()

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0      7    0    0    0    0    0    0    0    0    0  ...      0      0   
1      2    0    0    0    0    0    0    0    0    0  ...      0      0   
2      1    0    0    0    0    0    0    0    0    0  ...      0      0   
3      0    0    0    0    0    0    0    0    0    0  ...      0      0   
4      4    0    0    0    0    0    0    0    0    0  ...      0      0   

   28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0      0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0      0  

[5 rows x 785 columns]

In [5]:
mnist.shape

(10000, 785)

Image data has no nulls and nonnumaric but just for check it your confirmation

In [8]:
mnist.columns[mnist.isnull().sum()> 0]

Index([], dtype='object')

In [9]:
mnist.columns[mnist.dtypes == 'object']

Index([], dtype='object')

In [11]:
mnist = np.array(mnist)


In [13]:
mnist_x = mnist[: , 1:] 
mnist_y = mnist[: , 0]

In [14]:
mnist.shape

(10000, 785)

In [15]:
mnist_y

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [16]:
mnist_x.shape

(10000, 784)

In [18]:
mnist_x = mnist_x.reshape(-1,28,28,1)
mnist_x.shape

(10000, 28, 28, 1)

In [21]:
from keras.models import Sequential

In [24]:
from keras.layers import Conv2D , Flatten, Dense, Dropout

In [27]:
 from tensorflow.keras.layers import MaxPool2D

In [30]:
from keras.utils.np_utils import to_categorical

In [31]:
mnist_x = tf.keras.utils.normalize(mnist_x)
mnist_y = to_categorical(mnist_y)

In [32]:
mnist_y.shape

(10000, 10)

In [35]:
model = Sequential()
model.add(Conv2D(filters = 16, kernel_size = (5,5), activation = 'relu', padding = 'same',input_shape = (28,28,1) ))
model.add(MaxPool2D(pool_size = (2,2)))
model.add(Flatten())
model.add(Dense(128, activation = 'relu'))
model.add(Dropout(0.4))
model.add(Dense(10, activation = 'softmax'))

adam = tf.keras.optimizers.Adam()


model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [36]:
model.fit(mnist_x, mnist_y,epochs = 2, validation_split = 0.2)

Epoch 1/2
250/250 [==============================] - 9s 31ms/step - loss: 0.5611 - accuracy: 0.8249 - val_loss: 0.1513 - val_accuracy: 0.9550
Epoch 2/2
250/250 [==============================] - 7s 30ms/step - loss: 0.2103 - accuracy: 0.9339 - val_loss: 0.1041 - val_accuracy: 0.9665


In [39]:
pred_value = model.predict(mnist_x)

In [40]:
pred_value

array([[2.72938069e-05, 1.85257193e-07, 1.05971885e-04, ...,
        9.99047101e-01, 2.51866422e-05, 1.76252244e-04],
       [2.19194794e-06, 4.46288504e-05, 9.99565065e-01, ...,
        1.71283176e-07, 1.67651015e-05, 1.15968078e-07],
       [5.91904109e-06, 9.99185145e-01, 1.06319691e-04, ...,
        1.52350403e-04, 1.38294345e-04, 1.30090804e-04],
       ...,
       [2.24863557e-04, 2.30582533e-04, 4.24086938e-05, ...,
        1.41646527e-03, 6.39364263e-03, 3.86360846e-02],
       [1.17653915e-04, 9.03271866e-05, 1.22893880e-05, ...,
        3.37289894e-05, 9.55654308e-02, 8.90740557e-05],
       [1.98643756e-05, 6.19124933e-07, 4.47515107e-04, ...,
        6.06587358e-09, 4.27207215e-06, 1.66746258e-06]], dtype=float32)

In [41]:
pred_value = np.argmax(pred_value, axis = 1)

In [42]:
pred_value

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [44]:
from sklearn.metrics import confusion_matrix
tab = confusion_matrix(pred_value, np.argmax(mnist_y , axis = 1))
tab # from top actual and left right predict

array([[ 962,    0,    5,    0,    0,    1,    2,    3,    2,    2],
       [   1, 1123,    2,    0,    4,    0,    3,    4,   12,    6],
       [   2,    3, 1001,    7,    2,    0,    0,   13,    1,    1],
       [   2,    2,    4,  962,    0,    7,    0,    1,    6,    6],
       [   1,    0,    5,    0,  958,    0,    5,    3,    2,   16],
       [   1,    2,    0,   14,    0,  874,    6,    1,   10,    5],
       [   6,    1,    1,    0,    1,    5,  941,    0,    3,    1],
       [   1,    0,    3,    5,    1,    0,    0,  978,    1,    4],
       [   4,    4,   10,   17,    1,    4,    1,    4,  932,    7],
       [   0,    0,    1,    5,   15,    1,    0,   21,    5,  961]],
      dtype=int64)

In [45]:
tab.diagonal().sum() * 100 /tab.sum()

96.92

In [46]:
tab1 = confusion_matrix(np.argmax(mnist_y , axis = 1),pred_value)
tab1 # from top predict and left right actual

array([[ 962,    1,    2,    2,    1,    1,    6,    1,    4,    0],
       [   0, 1123,    3,    2,    0,    2,    1,    0,    4,    0],
       [   5,    2, 1001,    4,    5,    0,    1,    3,   10,    1],
       [   0,    0,    7,  962,    0,   14,    0,    5,   17,    5],
       [   0,    4,    2,    0,  958,    0,    1,    1,    1,   15],
       [   1,    0,    0,    7,    0,  874,    5,    0,    4,    1],
       [   2,    3,    0,    0,    5,    6,  941,    0,    1,    0],
       [   3,    4,   13,    1,    3,    1,    0,  978,    4,   21],
       [   2,   12,    1,    6,    2,   10,    3,    1,  932,    5],
       [   2,    6,    1,    6,   16,    5,    1,    4,    7,  961]],
      dtype=int64)